aws_profile		= "default"
aws_region		= "eu-west-2"
db_instance_clas	= "db.t2.micro"
dbname			= "database"
dbuser			= "dbuser"
dbpassword		= "dbpassword"
key_name                = "id_rsa"
public_key_path         = "/home/ubuntu/.ssh/id_rsa.pub"
dev_instance_type	= "t2.micro"
dev_ami			= "ami-00ee3b59e07408c27"
tag_vpc10-1-0-0-16	= "Principal"

