variable "aws_region" {}
variable "aws_profile" {}
#variable "localip" {}
variable "tag_vpc10-1-0-0-16" {}
variable "db_instance_class" {}
variable "dbname" {}
variable "dbuser" {}
variable "dbpassword" {}
variable "key_name" {}
variable "public_key_path" {}
variable "dev_instance_type" {}
variable "dev_ami" {}
variable "db_instance_type" {}
variable "db_ami" {}
